### ISSUE TITLE
ImportError: cannot import name 'VNCoreNLP'

### ISSUE THREAD

**Issue by ttran1904** [nguyenvanhieuvn/vncorenlp-wrapper#3]
I am using Python3 to run the word segmenter in VNCoreNLP. But I run into this error:

`from vncorenlp import VNCoreNLP`

> ImportError: cannot import name 'VNCoreNLP'

I have already copied all the necessary files from VNCoreNLP (both java and python) into my work directory.

**Comment by behitek** [comment]
Can you run [example.py](https://github.com/Hieunv1996/vncorenlp-wrapper/blob/master/example.py) file?

**Comment by ttran1904** [comment]
Yex, it works perfectly fine on example.py. But when I use it in my work file, it gives me the error.

Code: 
`
from io import open
from vncorenlp import VnCoreNLP


lst = [] # list of texts I want to scan
text = [] # tokenized word list. This is for later.

vn_stop  = open('vn-stop.txt', 'r').read()

vncore_nlp =VnCoreNLP(annotators="wseg pos ner parse")

for i in lst:

    # tokenize document string
    tokens = vncore_nlp.tokenize(i.lower(), str=False) 

    # remove stop words from tokens
    stopped_tokens = [i for i in tokens if not i in vn_stop]

    # add tokens to list
    texts.append(stopped_tokens)
`

**Comment by ttran1904** [comment]
I think I found the typo in my code. However, I am running into a second error that did not occur when I run example.py. Is this another error in my part? I am not sure why, but I used the same from vncorenlp import VNCoreNLP as before:

> tokens = vncore_nlp(i.lower(), str=False)
TypeError: 'VnCoreNLP' object is not callable

**Comment by ttran1904** [comment]
Nevermind. I think I found the typo in my code. Thank you so much :)
